version: '2'
services:
  web:
    image: tomcat
    ports: 
      - "8080:8080"
    volumes:
      - ./ProductWeb/target/ProductWeb.war:/usr/local/tomcat/webapps/ROOT.war
      - ./ProductWeb/target/ProductWeb:/usr/local/tomcat/webapps/ROOT
